/* tslint:disable */
/* eslint-disable */
/**
 * Event Management Public API
 * Public API for event discovery, registration, and attendee features
 * Version: 1.0.0
 * Generated by NSwag configuration
 */

import { Injectable, InjectionToken, Inject, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError, map } from 'rxjs/operators';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

// #region Enums

export enum EventStatus {
  Draft = 'Draft',
  Published = 'Published',
  Cancelled = 'Cancelled',
  Completed = 'Completed'
}

export enum EventVisibility {
  Public = 'Public',
  Private = 'Private',
  Unlisted = 'Unlisted'
}

export enum RegistrationStatus {
  Pending = 'Pending',
  Confirmed = 'Confirmed',
  Waitlisted = 'Waitlisted',
  Cancelled = 'Cancelled',
  CheckedIn = 'CheckedIn'
}

export enum RegistrationPriority {
  Normal = 'Normal',
  VIP = 'VIP',
  Speaker = 'Speaker',
  Staff = 'Staff'
}

export enum SessionType {
  Keynote = 'Keynote',
  Breakout = 'Breakout',
  Workshop = 'Workshop',
  Panel = 'Panel',
  Lightning = 'Lightning',
  Networking = 'Networking'
}

export enum SessionStatus {
  Draft = 'Draft',
  Scheduled = 'Scheduled',
  InProgress = 'InProgress',
  Completed = 'Completed',
  Cancelled = 'Cancelled'
}

export enum SocialEventType {
  Networking = 'Networking',
  Dinner = 'Dinner',
  Reception = 'Reception',
  Tour = 'Tour',
  Other = 'Other'
}

export enum SocialEventStatus {
  Draft = 'Draft',
  Published = 'Published',
  Cancelled = 'Cancelled',
  Completed = 'Completed'
}

// #endregion

// #region DTOs

export interface Event {
  id: string;
  title: string;
  description?: string;
  slug: string;
  startDate: Date;
  endDate: Date;
  venueName?: string;
  venueAddress?: string;
  isVirtual: boolean;
  virtualMeetingUrl?: string;
  maxAttendees?: number;
  currentAttendees: number;
  status: EventStatus;
  visibility: EventVisibility;
  registrationOpenDate?: Date;
  registrationCloseDate?: Date;
  imageUrl?: string;
  createdAt: Date;
  updatedAt?: Date;
}

export interface CreateEventRequest {
  title: string;
  description?: string;
  slug: string;
  startDate: Date;
  endDate: Date;
  venueName?: string;
  venueAddress?: string;
  isVirtual: boolean;
  virtualMeetingUrl?: string;
  maxAttendees?: number;
  visibility: EventVisibility;
  registrationOpenDate?: Date;
  registrationCloseDate?: Date;
  imageUrl?: string;
}

export interface UpdateEventRequest {
  title?: string;
  description?: string;
  slug?: string;
  startDate?: Date;
  endDate?: Date;
  venueName?: string;
  venueAddress?: string;
  isVirtual?: boolean;
  virtualMeetingUrl?: string;
  maxAttendees?: number;
  status?: EventStatus;
  visibility?: EventVisibility;
  registrationOpenDate?: Date;
  registrationCloseDate?: Date;
  imageUrl?: string;
}

export interface Registration {
  id: string;
  eventId: string;
  userId: string;
  status: RegistrationStatus;
  priority: RegistrationPriority;
  registrationData?: Record<string, any>;
  queuePosition?: number;
  confirmedAt?: Date;
  checkedInAt?: Date;
  createdAt: Date;
  updatedAt?: Date;
}

export interface RegistrationRequest {
  eventId: string;
  userId: string;
  priority?: RegistrationPriority;
  registrationData?: Record<string, any>;
}

export interface RegistrationResult {
  success: boolean;
  registration?: Registration;
  errorMessage?: string;
  queuePosition?: number;
}

export interface Session {
  id: string;
  eventId: string;
  title: string;
  description?: string;
  type: SessionType;
  status: SessionStatus;
  startTime: Date;
  endTime: Date;
  roomId?: string;
  roomName?: string;
  capacity?: number;
  level?: string;
  tags?: string[];
  speakers?: Speaker[];
  createdAt: Date;
  updatedAt?: Date;
}

export interface CreateSessionRequest {
  eventId: string;
  title: string;
  description?: string;
  type: SessionType;
  startTime: Date;
  endTime: Date;
  roomId?: string;
  capacity?: number;
  level?: string;
  tags?: string[];
  speakerIds?: string[];
}

export interface UpdateSessionRequest {
  title?: string;
  description?: string;
  type?: SessionType;
  status?: SessionStatus;
  startTime?: Date;
  endTime?: Date;
  roomId?: string;
  capacity?: number;
  level?: string;
  tags?: string[];
  speakerIds?: string[];
}

export interface Speaker {
  id: string;
  name: string;
  email: string;
  bio?: string;
  company?: string;
  title?: string;
  photoUrl?: string;
  linkedInUrl?: string;
  twitterHandle?: string;
  websiteUrl?: string;
  createdAt: Date;
  updatedAt?: Date;
}

export interface CreateSpeakerRequest {
  name: string;
  email: string;
  bio?: string;
  company?: string;
  title?: string;
  photoUrl?: string;
  linkedInUrl?: string;
  twitterHandle?: string;
  websiteUrl?: string;
}

export interface UpdateSpeakerRequest {
  name?: string;
  email?: string;
  bio?: string;
  company?: string;
  title?: string;
  photoUrl?: string;
  linkedInUrl?: string;
  twitterHandle?: string;
  websiteUrl?: string;
}

export interface SocialEvent {
  id: string;
  eventId: string;
  title: string;
  description?: string;
  type: SocialEventType;
  status: SocialEventStatus;
  location?: string;
  startTime: Date;
  endTime: Date;
  maxCapacity?: number;
  currentRsvpCount: number;
  rsvpRequired: boolean;
  createdAt: Date;
  updatedAt?: Date;
}

export interface CreateSocialEventRequest {
  eventId: string;
  title: string;
  description?: string;
  type: SocialEventType;
  location?: string;
  startTime: Date;
  endTime: Date;
  maxCapacity?: number;
  rsvpRequired: boolean;
}

export interface SocialEventRsvp {
  id: string;
  socialEventId: string;
  userId: string;
  status: string;
  createdAt: Date;
  updatedAt?: Date;
}

export interface PagedResult<T> {
  items: T[];
  totalCount: number;
  currentPage: number;
  totalPages: number;
  pageSize: number;
  hasPrevious: boolean;
  hasNext: boolean;
}

export interface User {
  id: string;
  email: string;
  fullName: string;
  avatarUrl?: string;
  createdAt: Date;
  updatedAt?: Date;
}

// #endregion

// #region API Client

@Injectable({
  providedIn: 'root'
})
export class ApiClient {
  private baseUrl: string;

  constructor(
    private http: HttpClient,
    @Optional() @Inject(API_BASE_URL) baseUrl?: string
  ) {
    this.baseUrl = baseUrl ?? '';
  }

  // #region Events

  getEvents(page = 1, pageSize = 20, status?: EventStatus): Observable<PagedResult<Event>> {
    let params = new HttpParams()
      .set('page', page.toString())
      .set('pageSize', pageSize.toString());
    
    if (status) {
      params = params.set('status', status);
    }

    return this.http.get<PagedResult<Event>>(`${this.baseUrl}/api/events`, { params })
      .pipe(catchError(this.handleError));
  }

  getEvent(id: string): Observable<Event> {
    return this.http.get<Event>(`${this.baseUrl}/api/events/${id}`)
      .pipe(catchError(this.handleError));
  }

  getEventBySlug(slug: string): Observable<Event> {
    return this.http.get<Event>(`${this.baseUrl}/api/events/slug/${slug}`)
      .pipe(catchError(this.handleError));
  }

  createEvent(request: CreateEventRequest): Observable<Event> {
    return this.http.post<Event>(`${this.baseUrl}/api/events`, request)
      .pipe(catchError(this.handleError));
  }

  updateEvent(id: string, request: UpdateEventRequest): Observable<Event> {
    return this.http.put<Event>(`${this.baseUrl}/api/events/${id}`, request)
      .pipe(catchError(this.handleError));
  }

  deleteEvent(id: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/api/events/${id}`)
      .pipe(catchError(this.handleError));
  }

  // #endregion

  // #region Registration

  registerForEvent(request: RegistrationRequest): Observable<RegistrationResult> {
    return this.http.post<RegistrationResult>(`${this.baseUrl}/api/registration`, request)
      .pipe(catchError(this.handleError));
  }

  getRegistration(id: string): Observable<Registration> {
    return this.http.get<Registration>(`${this.baseUrl}/api/registration/${id}`)
      .pipe(catchError(this.handleError));
  }

  getUserRegistrations(userId: string): Observable<Registration[]> {
    return this.http.get<Registration[]>(`${this.baseUrl}/api/registration/user/${userId}`)
      .pipe(catchError(this.handleError));
  }

  getEventRegistrations(eventId: string, page = 1, pageSize = 50): Observable<PagedResult<Registration>> {
    const params = new HttpParams()
      .set('page', page.toString())
      .set('pageSize', pageSize.toString());

    return this.http.get<PagedResult<Registration>>(`${this.baseUrl}/api/registration/event/${eventId}`, { params })
      .pipe(catchError(this.handleError));
  }

  cancelRegistration(id: string, reason?: string): Observable<RegistrationResult> {
    return this.http.post<RegistrationResult>(`${this.baseUrl}/api/registration/${id}/cancel`, { reason })
      .pipe(catchError(this.handleError));
  }

  checkInRegistration(id: string): Observable<RegistrationResult> {
    return this.http.post<RegistrationResult>(`${this.baseUrl}/api/registration/${id}/checkin`, {})
      .pipe(catchError(this.handleError));
  }

  getQueuePosition(eventId: string, userId: string): Observable<{ position: number; estimatedWait?: number }> {
    return this.http.get<{ position: number; estimatedWait?: number }>(
      `${this.baseUrl}/api/registration/queue/${eventId}/${userId}`)
      .pipe(catchError(this.handleError));
  }

  // #endregion

  // #region Sessions

  getSessions(eventId: string, page = 1, pageSize = 20): Observable<PagedResult<Session>> {
    const params = new HttpParams()
      .set('page', page.toString())
      .set('pageSize', pageSize.toString());

    return this.http.get<PagedResult<Session>>(`${this.baseUrl}/api/events/${eventId}/sessions`, { params })
      .pipe(catchError(this.handleError));
  }

  getSession(id: string): Observable<Session> {
    return this.http.get<Session>(`${this.baseUrl}/api/sessions/${id}`)
      .pipe(catchError(this.handleError));
  }

  createSession(request: CreateSessionRequest): Observable<Session> {
    return this.http.post<Session>(`${this.baseUrl}/api/sessions`, request)
      .pipe(catchError(this.handleError));
  }

  updateSession(id: string, request: UpdateSessionRequest): Observable<Session> {
    return this.http.put<Session>(`${this.baseUrl}/api/sessions/${id}`, request)
      .pipe(catchError(this.handleError));
  }

  deleteSession(id: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/api/sessions/${id}`)
      .pipe(catchError(this.handleError));
  }

  // #endregion

  // #region Speakers

  getSpeakers(page = 1, pageSize = 20): Observable<PagedResult<Speaker>> {
    const params = new HttpParams()
      .set('page', page.toString())
      .set('pageSize', pageSize.toString());

    return this.http.get<PagedResult<Speaker>>(`${this.baseUrl}/api/speakers`, { params })
      .pipe(catchError(this.handleError));
  }

  getSpeaker(id: string): Observable<Speaker> {
    return this.http.get<Speaker>(`${this.baseUrl}/api/speakers/${id}`)
      .pipe(catchError(this.handleError));
  }

  createSpeaker(request: CreateSpeakerRequest): Observable<Speaker> {
    return this.http.post<Speaker>(`${this.baseUrl}/api/speakers`, request)
      .pipe(catchError(this.handleError));
  }

  updateSpeaker(id: string, request: UpdateSpeakerRequest): Observable<Speaker> {
    return this.http.put<Speaker>(`${this.baseUrl}/api/speakers/${id}`, request)
      .pipe(catchError(this.handleError));
  }

  deleteSpeaker(id: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/api/speakers/${id}`)
      .pipe(catchError(this.handleError));
  }

  // #endregion

  // #region Social Events

  getSocialEvents(eventId: string): Observable<SocialEvent[]> {
    return this.http.get<SocialEvent[]>(`${this.baseUrl}/api/events/${eventId}/social-events`)
      .pipe(catchError(this.handleError));
  }

  getSocialEvent(id: string): Observable<SocialEvent> {
    return this.http.get<SocialEvent>(`${this.baseUrl}/api/social-events/${id}`)
      .pipe(catchError(this.handleError));
  }

  createSocialEvent(request: CreateSocialEventRequest): Observable<SocialEvent> {
    return this.http.post<SocialEvent>(`${this.baseUrl}/api/social-events`, request)
      .pipe(catchError(this.handleError));
  }

  rsvpToSocialEvent(socialEventId: string, userId: string): Observable<SocialEventRsvp> {
    return this.http.post<SocialEventRsvp>(`${this.baseUrl}/api/social-events/${socialEventId}/rsvp`, { userId })
      .pipe(catchError(this.handleError));
  }

  cancelSocialEventRsvp(socialEventId: string, userId: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/api/social-events/${socialEventId}/rsvp/${userId}`)
      .pipe(catchError(this.handleError));
  }

  // #endregion

  // #region User

  getCurrentUser(): Observable<User> {
    return this.http.get<User>(`${this.baseUrl}/api/user/me`)
      .pipe(catchError(this.handleError));
  }

  updateProfile(request: Partial<User>): Observable<User> {
    return this.http.put<User>(`${this.baseUrl}/api/user/profile`, request)
      .pipe(catchError(this.handleError));
  }

  // #endregion

  // #region Error Handling

  private handleError(error: any): Observable<never> {
    let errorMessage = 'An error occurred';
    
    if (error.error instanceof ErrorEvent) {
      // Client-side error
      errorMessage = error.error.message;
    } else if (error.status) {
      // Server-side error
      errorMessage = `Error ${error.status}: ${error.error?.message || error.statusText}`;
    }

    console.error('API Error:', errorMessage, error);
    return throwError(() => new ApiException(error.status, errorMessage, error));
  }

  // #endregion
}

export class ApiException {
  constructor(
    public status: number,
    public message: string,
    public response?: any
  ) {}
}

// #endregion
